# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/1.EE/FPGA/VerilogWorks/UART/UART.srcs/sources_1/ip/FIFO_UART/FIFO_UART.xci
# IP: The module: 'FIFO_UART' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1.EE/FPGA/VerilogWorks/UART/UART.srcs/sources_1/ip/FIFO_UART/FIFO_UART.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_UART'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/1.EE/FPGA/VerilogWorks/UART/UART.srcs/sources_1/ip/FIFO_UART/FIFO_UART_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_UART'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/1.EE/FPGA/VerilogWorks/UART/UART.srcs/sources_1/ip/FIFO_UART/FIFO_UART_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_UART'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/1.EE/FPGA/VerilogWorks/UART/UART.srcs/sources_1/ip/FIFO_UART/FIFO_UART.xci
# IP: The module: 'FIFO_UART' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/1.EE/FPGA/VerilogWorks/UART/UART.srcs/sources_1/ip/FIFO_UART/FIFO_UART.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_UART'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/1.EE/FPGA/VerilogWorks/UART/UART.srcs/sources_1/ip/FIFO_UART/FIFO_UART_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_UART'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/1.EE/FPGA/VerilogWorks/UART/UART.srcs/sources_1/ip/FIFO_UART/FIFO_UART_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_UART'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
